POST http://localhost:3000/api/v1/groups
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZWFlYzhkMi1lMDU5LTQyN2UtYjc2My0wMGYwMDU3NTVhNjAiLCJpYXQiOjE2NjU0MDgxNjAsImV4cCI6MTY2NTQxMTc2MH0.S3mohZrGewLVxHZ747OsxQKVLcfw_vzAw7D1hAwvgp8


{
  "name": "reza is king",
  "description": "second group"
}
