GET http://localhost:3000/api/v1/connection_requests
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmM2I1ODQ5OS1hNTUwLTRjODYtOTY5MC00N2UyOWU5ZWMxMGQiLCJpYXQiOjE2NTMzOTkyOTksImV4cCI6MTY1MzQwMjg5OX0.H8QJ2iSYKCxppcXijmuWNdYj7Wah9dcPq7OXyNVIP4s